### ISSUE TITLE
Complete HTML versions of layouts

### ISSUE THREAD

**Issue by jmejia** [marlabrizel/jurassic_parka#10]
We need HTML versions of the following layouts ready by the second half of Tuesday afternoon

* Homepage
* Items index and show
* Cart

**Comment by marlabrizel** [comment]
Homepage is complete

**Comment by jmejia** [comment]
* Add bootstrap
* Make sure that no text is on background image
* Set a default sans-serif font (open-sans?)
* Make sure your images have padding and are also placed in white boxes
*  navbar style navigation instead of pills
