### ISSUE TITLE
Authenticated User

### ISSUE THREAD

**Issue by jmejia** [marlabrizel/jurassic_parka#17]
As a visitor
When I visit "/"
Then I should see a link for "Login"
And when I click link "Create Account"
Then my current page should be "/dashboard"
And I should see a message in the navbar that says "Logged in as SOME_USER"
And I should see my profile information
And I should not see a link for "Login"
And I should see a link for "Logout"

When I click "Logout"
Then I should see see "Login"
And I should not see "Logout"

**Comment by mitchashby16** [comment]
Drew, for this you'll have to create a users table as well
