### ISSUE TITLE
Admin Dashboard

### ISSUE THREAD

**Issue by jmejia** [marlabrizel/jurassic_parka#22]
As an Admin
When I visit "/admin/dashboard"
I will see a heading on the page that says "Admin Dashboard"

As a registered user
When I visit "/admin/dashboard"
I get a 404

As an unregistered user
When I visit "/admin/dashboard"
I get a 404

**Comment by marlabrizel** [comment]
This story includes setting up user authorization (running a migration to add role column to users table, doing enum roles, etc.) We originally had a card for that, but it seems to have disappeared so putting a note in here so we don't forget.
